/*
 * ISO 14819-2 header file: supplementary information entries
 * DO NOT EDIT: automatically generated by gentables.py from CSV files
 */

#ifndef _ISO14819_2_SUPPLEMENTARY_H_INCLUDED
#define _ISO14819_2_SUPPLEMENTARY_H_INCLUDED

const char Supplementary_S_01[] PROGMEM = "heavy lorries are recommended to avoid the area";
const char Supplementary_S_02[] PROGMEM = "follow signs";
const char Supplementary_S_03[] PROGMEM = "follow diversion signs";
const char Supplementary_S_04[] PROGMEM = "diversion in operation";
const char Supplementary_S_05[] PROGMEM = "no suitable diversion available";
const char Supplementary_S_06[] PROGMEM = "diversion is no longer recommended";
const char Supplementary_S_07[] PROGMEM = "for exceptional loads only";
const char Supplementary_S_08[] PROGMEM = "for heavy vehicles only";
const char Supplementary_S_09[] PROGMEM = "for cars and light vehicles only";
const char Supplementary_S_0A[] PROGMEM = "snowploughs in use";
const char Supplementary_S_0B[] PROGMEM = "gritting vehicles in use";
const char Supplementary_S_0C[] PROGMEM = "drive carefully";
const char Supplementary_S_0D[] PROGMEM = "keep your distance";
const char Supplementary_S_0E[] PROGMEM = "observe signals";
const char Supplementary_S_0F[] PROGMEM = "overtake with care";
const char Supplementary_S_10[] PROGMEM = "cross junction with care";
const char Supplementary_S_11[] PROGMEM = "no overtaking";
const char Supplementary_S_12[] PROGMEM = "use headlights";
const char Supplementary_S_13[] PROGMEM = "use fog lights";
const char Supplementary_S_14[] PROGMEM = "do not leave your vehicle";
const char Supplementary_S_15[] PROGMEM = "switch off engine";
const char Supplementary_S_16[] PROGMEM = "close all windows. Turn off heater and vents";
const char Supplementary_S_17[] PROGMEM = "test your brakes";
const char Supplementary_S_18[] PROGMEM = "winter equipment recommended";
const char Supplementary_S_19[] PROGMEM = "snow chains recommended";
const char Supplementary_S_1A[] PROGMEM = "snow chains mandatory";
const char Supplementary_S_1B[] PROGMEM = "keep to the left";
const char Supplementary_S_1C[] PROGMEM = "keep to the right";
const char Supplementary_S_1D[] PROGMEM = "use hard shoulder as lane";
const char Supplementary_S_1E[] PROGMEM = "do not drive on the hard shoulder";
const char Supplementary_S_1F[] PROGMEM = "in the opposite direction";
const char Supplementary_S_20[] PROGMEM = "in the opposing lanes";
const char Supplementary_S_21[] PROGMEM = "in the overtaking lane";
const char Supplementary_S_22[] PROGMEM = "in the crawler lane";
const char Supplementary_S_23[] PROGMEM = "in the right lane";
const char Supplementary_S_24[] PROGMEM = "in the middle lane";
const char Supplementary_S_25[] PROGMEM = "in the left lane";
const char Supplementary_S_26[] PROGMEM = "on the roadway";
const char Supplementary_S_27[] PROGMEM = "police directing traffic";
const char Supplementary_S_28[] PROGMEM = "police in attendance";
const char Supplementary_S_29[] PROGMEM = "extra police patrols in operation";
const char Supplementary_S_2A[] PROGMEM = "rescue and recovery work in progress";
const char Supplementary_S_2B[] PROGMEM = "look out for flagman";
const char Supplementary_S_2C[] PROGMEM = "why not park-and-ride?";
const char Supplementary_S_2D[] PROGMEM = "why not try public transport?";
const char Supplementary_S_2E[] PROGMEM = "only travel if absolutely necessary";
const char Supplementary_S_2F[] PROGMEM = "increased risk of accident";
const char Supplementary_S_30[] PROGMEM = "on bridges";
const char Supplementary_S_31[] PROGMEM = "in shaded areas";
const char Supplementary_S_32[] PROGMEM = "entering or leaving tunnels";
const char Supplementary_S_33[] PROGMEM = "winter closure";
const char Supplementary_S_34[] PROGMEM = "batch service in progress";
const char Supplementary_S_35[] PROGMEM = "the north";
const char Supplementary_S_36[] PROGMEM = "the north-east";
const char Supplementary_S_37[] PROGMEM = "the east";
const char Supplementary_S_38[] PROGMEM = "the south-east";
const char Supplementary_S_39[] PROGMEM = "the south";
const char Supplementary_S_3A[] PROGMEM = "the south-west";
const char Supplementary_S_3B[] PROGMEM = "the west";
const char Supplementary_S_3C[] PROGMEM = "the north-west";
const char Supplementary_S_3D[] PROGMEM = "follow special diversion markers";
const char Supplementary_S_3E[] PROGMEM = "do not follow diversion signs";
const char Supplementary_S_3F[] PROGMEM = "follow local diversion";
const char Supplementary_S_40[] PROGMEM = "compulsory diversion in operation";
const char Supplementary_S_41[] PROGMEM = "for petrol-engined vehicles only";
const char Supplementary_S_42[] PROGMEM = "for diesel-engined vehicles only";
const char Supplementary_S_43[] PROGMEM = "for LPG vehicles only";
const char Supplementary_S_44[] PROGMEM = "local drivers are recommended to avoid the area";
const char Supplementary_S_45[] PROGMEM = "for 4-wheel-drive with snow tyres or chains only";
const char Supplementary_S_46[] PROGMEM = "in the median";
const char Supplementary_S_47[] PROGMEM = "for cars only";
const char Supplementary_S_48[] PROGMEM = "for light vehicles only";
const char Supplementary_S_49[] PROGMEM = "for vehicles with catalytic converters";
const char Supplementary_S_4A[] PROGMEM = "for vehicles without catalytic converters";
const char Supplementary_S_4B[] PROGMEM = "for cars with trailers only";
const char Supplementary_S_4C[] PROGMEM = "for cars with caravans only";
const char Supplementary_S_4D[] PROGMEM = "for vehicles with trailers only";
const char Supplementary_S_4E[] PROGMEM = "for heavy lorries only";
const char Supplementary_S_4F[] PROGMEM = "for buses only";
const char Supplementary_S_50[] PROGMEM = "for articulated vehicles only";
const char Supplementary_S_51[] PROGMEM = "for high-sided vehicles only";
const char Supplementary_S_52[] PROGMEM = "for hazardous loads only";
const char Supplementary_S_53[] PROGMEM = "for abnormal loads only";
const char Supplementary_S_54[] PROGMEM = "with even-numbered registration plates";
const char Supplementary_S_55[] PROGMEM = "with odd-numbered registration plates";
const char Supplementary_S_56[] PROGMEM = "for all vehicles";
const char Supplementary_S_58[] PROGMEM = "for through traffic";
const char Supplementary_S_59[] PROGMEM = "for rail services";
const char Supplementary_S_5A[] PROGMEM = "on the underground";
const char Supplementary_S_5B[] PROGMEM = "danger";
const char Supplementary_S_5C[] PROGMEM = "repairs in progress";
const char Supplementary_S_5D[] PROGMEM = "pilot car in operation";
const char Supplementary_S_5E[] PROGMEM = "emergency vehicles at scene";
const char Supplementary_S_5F[] PROGMEM = "traffic being directed around accident area";
const char Supplementary_S_60[] PROGMEM = "danger of explosion";
const char Supplementary_S_61[] PROGMEM = "danger of fire";
const char Supplementary_S_62[] PROGMEM = "radiation hazard";
const char Supplementary_S_63[] PROGMEM = "toxic leak";
const char Supplementary_S_64[] PROGMEM = "firemen directing traffic";
const char Supplementary_S_65[] PROGMEM = "police speed checks in operation";
const char Supplementary_S_66[] PROGMEM = "mandatory speed limit in force";
const char Supplementary_S_67[] PROGMEM = "speed limit in force for heavy vehicles";
const char Supplementary_S_68[] PROGMEM = "reduce your speed";
const char Supplementary_S_69[] PROGMEM = "observe speed limits";
const char Supplementary_S_6A[] PROGMEM = "observe recommended speed";
const char Supplementary_S_6B[] PROGMEM = "snow chains required";
const char Supplementary_S_6C[] PROGMEM = "snow chains or tyres reqired";
const char Supplementary_S_6D[] PROGMEM = "helicopter rescue in progress";
const char Supplementary_S_6E[] PROGMEM = "several accidents have taken place";
const char Supplementary_S_6F[] PROGMEM = "drive with extreme caution";
const char Supplementary_S_70[] PROGMEM = "approach with care";
const char Supplementary_S_71[] PROGMEM = "increase normal following distance";
const char Supplementary_S_72[] PROGMEM = "do not allow unnecessary gaps";
const char Supplementary_S_73[] PROGMEM = "follow the vehicle in front, smoothly";
const char Supplementary_S_74[] PROGMEM = "do not slow down unneccessarily";
const char Supplementary_S_75[] PROGMEM = "observe signs";
const char Supplementary_S_76[] PROGMEM = "use hazard warning lights";
const char Supplementary_S_77[] PROGMEM = "no smoking";
const char Supplementary_S_78[] PROGMEM = "no naked flames";
const char Supplementary_S_79[] PROGMEM = "switch off mobile phones and two-way radios";
const char Supplementary_S_7A[] PROGMEM = "allow emergency vehicles to pass";
const char Supplementary_S_7B[] PROGMEM = "clear a lane for emergency vehicles";
const char Supplementary_S_7C[] PROGMEM = "pull over to the edge of the roadway";
const char Supplementary_S_7D[] PROGMEM = "wait for escort vehicle";
const char Supplementary_S_7E[] PROGMEM = "in emergency, wait for police patrol";
const char Supplementary_S_80[] PROGMEM = "stop at next safe place";
const char Supplementary_S_81[] PROGMEM = "clear a lane for snowploughs and gritting vehicles";
const char Supplementary_S_83[] PROGMEM = "use right lane";
const char Supplementary_S_84[] PROGMEM = "use left lane";
const char Supplementary_S_85[] PROGMEM = "heavy vehicles use right lane";
const char Supplementary_S_86[] PROGMEM = "heavy vehicles use left lane";
const char Supplementary_S_88[] PROGMEM = "stop at next service area";
const char Supplementary_S_8D[] PROGMEM = "on the right";
const char Supplementary_S_8E[] PROGMEM = "in the centre";
const char Supplementary_S_8F[] PROGMEM = "on the left";
const char Supplementary_S_90[] PROGMEM = "in the bus lane";
const char Supplementary_S_91[] PROGMEM = "in the carpool lane";
const char Supplementary_S_92[] PROGMEM = "on the hard shoulder";
const char Supplementary_S_93[] PROGMEM = "in the emergency lane";
const char Supplementary_S_94[] PROGMEM = "on the opposite carriageway";
const char Supplementary_S_95[] PROGMEM = "in the heavy vehicle lane";
const char Supplementary_S_96[] PROGMEM = "in the local lane";
const char Supplementary_S_97[] PROGMEM = "due to heat";
const char Supplementary_S_98[] PROGMEM = "due to frost";
const char Supplementary_S_99[] PROGMEM = "for ferry service";
const char Supplementary_S_9A[] PROGMEM = "for roads in";
const char Supplementary_S_9B[] PROGMEM = "in the through traffic lane";
const char Supplementary_S_9C[] PROGMEM = "in the express lane";
const char Supplementary_S_9D[] PROGMEM = "in the connecting carriageway";
const char Supplementary_S_9E[] PROGMEM = "in the parallel carriageway";
const char Supplementary_S_9F[] PROGMEM = "in the right-hand parallel carriageway";
const char Supplementary_S_A0[] PROGMEM = "in the left-hand parallel carriageway";
const char Supplementary_S_A1[] PROGMEM = "in tunnels";
const char Supplementary_S_A2[] PROGMEM = "on slip roads";
const char Supplementary_S_A3[] PROGMEM = "at high altitudes";
const char Supplementary_S_A4[] PROGMEM = "in low-lying areas";
const char Supplementary_S_A5[] PROGMEM = "around a bend in the road";
const char Supplementary_S_A6[] PROGMEM = "over the crest of a hill";
const char Supplementary_S_A7[] PROGMEM = "in the city centre";
const char Supplementary_S_A8[] PROGMEM = "in the inner city area";
const char Supplementary_S_A9[] PROGMEM = "in the slow vehicle lane";
const char Supplementary_S_AA[] PROGMEM = "in the turning lane";
const char Supplementary_S_AB[] PROGMEM = "due to an earlier accident";
const char Supplementary_S_AC[] PROGMEM = "due to shear weight of traffic";
const char Supplementary_S_AD[] PROGMEM = "due to large numbers of visitors";
const char Supplementary_S_AE[] PROGMEM = "due to holiday traffic";
const char Supplementary_S_AF[] PROGMEM = "due to technical problems";
const char Supplementary_S_B0[] PROGMEM = "towards town";
const char Supplementary_S_B1[] PROGMEM = "from town";
const char Supplementary_S_B2[] PROGMEM = "on entry into the country";
const char Supplementary_S_B3[] PROGMEM = "on leaving the country";
const char Supplementary_S_B4[] PROGMEM = "do not throw out any burning objects";
const char Supplementary_S_B5[] PROGMEM = "traffic wardens directing traffic";
const char Supplementary_S_B9[] PROGMEM = "due to falling ice";
const char Supplementary_S_BF[] PROGMEM = "snow tyres recommended";
const char Supplementary_S_C0[] PROGMEM = "snow tyres mandatory";
const char Supplementary_S_C3[] PROGMEM = "use through traffic lanes";
const char Supplementary_S_C4[] PROGMEM = "use local traffic lanes";
const char Supplementary_S_C5[] PROGMEM = "use left-hand parallel carriageway";
const char Supplementary_S_C6[] PROGMEM = "use right-hand parallel carriageway";
const char Supplementary_S_C7[] PROGMEM = "use heavy vehicle lane";
const char Supplementary_S_C8[] PROGMEM = "due to an earlier incident";
const char Supplementary_S_C9[] PROGMEM = "why not ride share?";
const char Supplementary_S_CA[] PROGMEM = "is this your no-ride day?";
const char Supplementary_S_CB[] PROGMEM = "due to an earlier event";
const char Supplementary_S_CC[] PROGMEM = "please use rail service";
const char Supplementary_S_CD[] PROGMEM = "please use underground service";
const char Supplementary_S_CE[] PROGMEM = "please use tram service";
const char Supplementary_S_CF[] PROGMEM = "please use bus service";
const char Supplementary_S_D0[] PROGMEM = "for a limited time";
const char Supplementary_S_D1[] PROGMEM = "your parking ticket covers the return ride";
const char Supplementary_S_D2[] PROGMEM = "avoid the rush hour";
const char Supplementary_S_D3[] PROGMEM = "for holiday traffic";
const char Supplementary_S_D4[] PROGMEM = "for residents";
const char Supplementary_S_D5[] PROGMEM = "several times";
const char Supplementary_S_D6[] PROGMEM = "during the day time";
const char Supplementary_S_D7[] PROGMEM = "during off-peak periods";
const char Supplementary_S_D8[] PROGMEM = "during the night";
const char Supplementary_S_D9[] PROGMEM = "until further notice";
const char Supplementary_S_DA[] PROGMEM = "for arrivals";
const char Supplementary_S_DB[] PROGMEM = "for departures";
const char Supplementary_S_DC[] PROGMEM = "access only";
const char Supplementary_S_DD[] PROGMEM = "only";
const char Supplementary_S_DE[] PROGMEM = "except";
const char Supplementary_S_DF[] PROGMEM = "for long distance traffic";
const char Supplementary_S_E0[] PROGMEM = "for local traffic";
const char Supplementary_S_E1[] PROGMEM = "for regional traffic";
const char Supplementary_S_E2[] PROGMEM = "unconfirmed report";
const char Supplementary_S_E3[] PROGMEM = "on manual payment lanes";
const char Supplementary_S_E7[] PROGMEM = "sorry for any delay";
const char Supplementary_S_E8[] PROGMEM = "for roads leading towards";
const char Supplementary_S_E9[] PROGMEM = "for roads from";
const char Supplementary_S_EA[] PROGMEM = "we are grateful for your cooperation";
const char Supplementary_S_EB[] PROGMEM = "Traffic queue length decreasing at an average rate of 10 km/hr";
const char Supplementary_S_EC[] PROGMEM = "Traffic queue length decreasing at an average rate of 20 km/hr";
const char Supplementary_S_ED[] PROGMEM = "Traffic queue length decreasing at an average rate of 30 km/hr";
const char Supplementary_S_EE[] PROGMEM = "Traffic queue length decreasing at an average rate of 40 km/hr";
const char Supplementary_S_EF[] PROGMEM = "leave your vehicle. Proceed to next save place";
const char Supplementary_S_F0[] PROGMEM = "for visitors";
const char Supplementary_S_F1[] PROGMEM = "in the roadworks area";
const char Supplementary_S_F2[] PROGMEM = "from";
const char Supplementary_S_F3[] PROGMEM = "to";
const char Supplementary_S_F4[] PROGMEM = "in";
const char Supplementary_S_F5[] PROGMEM = "Traffic queue length increasing";
const char Supplementary_S_F6[] PROGMEM = "Traffic queue length increasing at an average rate of 10 km/hr";
const char Supplementary_S_F7[] PROGMEM = "Traffic queue length increasing at an average rate of 20 km/hr";
const char Supplementary_S_F8[] PROGMEM = "Traffic queue length increasing at an average rate of 30 km/hr";
const char Supplementary_S_F9[] PROGMEM = "Traffic queue length increasing at an average rate of 40 km/hr";
const char Supplementary_S_FA[] PROGMEM = "very frequent service";
const char Supplementary_S_FB[] PROGMEM = "frequent service";
const char Supplementary_S_FC[] PROGMEM = "fairly frequent service";
const char Supplementary_S_FD[] PROGMEM = "regular service";
const char Supplementary_S_FF[] PROGMEM = "Traffic queue length decreasing";

const TRDSTMCSupplementaryEntry ISO14819_2_Supplementary[233] PROGMEM = {
	{0x01, Supplementary_S_01},
	{0x02, Supplementary_S_02},
	{0x03, Supplementary_S_03},
	{0x04, Supplementary_S_04},
	{0x05, Supplementary_S_05},
	{0x06, Supplementary_S_06},
	{0x07, Supplementary_S_07},
	{0x08, Supplementary_S_08},
	{0x09, Supplementary_S_09},
	{0x0A, Supplementary_S_0A},
	{0x0B, Supplementary_S_0B},
	{0x0C, Supplementary_S_0C},
	{0x0D, Supplementary_S_0D},
	{0x0E, Supplementary_S_0E},
	{0x0F, Supplementary_S_0F},
	{0x10, Supplementary_S_10},
	{0x11, Supplementary_S_11},
	{0x12, Supplementary_S_12},
	{0x13, Supplementary_S_13},
	{0x14, Supplementary_S_14},
	{0x15, Supplementary_S_15},
	{0x16, Supplementary_S_16},
	{0x17, Supplementary_S_17},
	{0x18, Supplementary_S_18},
	{0x19, Supplementary_S_19},
	{0x1A, Supplementary_S_1A},
	{0x1B, Supplementary_S_1B},
	{0x1C, Supplementary_S_1C},
	{0x1D, Supplementary_S_1D},
	{0x1E, Supplementary_S_1E},
	{0x1F, Supplementary_S_1F},
	{0x20, Supplementary_S_20},
	{0x21, Supplementary_S_21},
	{0x22, Supplementary_S_22},
	{0x23, Supplementary_S_23},
	{0x24, Supplementary_S_24},
	{0x25, Supplementary_S_25},
	{0x26, Supplementary_S_26},
	{0x27, Supplementary_S_27},
	{0x28, Supplementary_S_28},
	{0x29, Supplementary_S_29},
	{0x2A, Supplementary_S_2A},
	{0x2B, Supplementary_S_2B},
	{0x2C, Supplementary_S_2C},
	{0x2D, Supplementary_S_2D},
	{0x2E, Supplementary_S_2E},
	{0x2F, Supplementary_S_2F},
	{0x30, Supplementary_S_30},
	{0x31, Supplementary_S_31},
	{0x32, Supplementary_S_32},
	{0x33, Supplementary_S_33},
	{0x34, Supplementary_S_34},
	{0x35, Supplementary_S_35},
	{0x36, Supplementary_S_36},
	{0x37, Supplementary_S_37},
	{0x38, Supplementary_S_38},
	{0x39, Supplementary_S_39},
	{0x3A, Supplementary_S_3A},
	{0x3B, Supplementary_S_3B},
	{0x3C, Supplementary_S_3C},
	{0x3D, Supplementary_S_3D},
	{0x3E, Supplementary_S_3E},
	{0x3F, Supplementary_S_3F},
	{0x40, Supplementary_S_40},
	{0x41, Supplementary_S_41},
	{0x42, Supplementary_S_42},
	{0x43, Supplementary_S_43},
	{0x44, Supplementary_S_44},
	{0x45, Supplementary_S_45},
	{0x46, Supplementary_S_46},
	{0x47, Supplementary_S_47},
	{0x48, Supplementary_S_48},
	{0x49, Supplementary_S_49},
	{0x4A, Supplementary_S_4A},
	{0x4B, Supplementary_S_4B},
	{0x4C, Supplementary_S_4C},
	{0x4D, Supplementary_S_4D},
	{0x4E, Supplementary_S_4E},
	{0x4F, Supplementary_S_4F},
	{0x50, Supplementary_S_50},
	{0x51, Supplementary_S_51},
	{0x52, Supplementary_S_52},
	{0x53, Supplementary_S_53},
	{0x54, Supplementary_S_54},
	{0x55, Supplementary_S_55},
	{0x56, Supplementary_S_56},
	{0x58, Supplementary_S_58},
	{0x59, Supplementary_S_59},
	{0x5A, Supplementary_S_5A},
	{0x5B, Supplementary_S_5B},
	{0x5C, Supplementary_S_5C},
	{0x5D, Supplementary_S_5D},
	{0x5E, Supplementary_S_5E},
	{0x5F, Supplementary_S_5F},
	{0x60, Supplementary_S_60},
	{0x61, Supplementary_S_61},
	{0x62, Supplementary_S_62},
	{0x63, Supplementary_S_63},
	{0x64, Supplementary_S_64},
	{0x65, Supplementary_S_65},
	{0x66, Supplementary_S_66},
	{0x67, Supplementary_S_67},
	{0x68, Supplementary_S_68},
	{0x69, Supplementary_S_69},
	{0x6A, Supplementary_S_6A},
	{0x6B, Supplementary_S_6B},
	{0x6C, Supplementary_S_6C},
	{0x6D, Supplementary_S_6D},
	{0x6E, Supplementary_S_6E},
	{0x6F, Supplementary_S_6F},
	{0x70, Supplementary_S_70},
	{0x71, Supplementary_S_71},
	{0x72, Supplementary_S_72},
	{0x73, Supplementary_S_73},
	{0x74, Supplementary_S_74},
	{0x75, Supplementary_S_75},
	{0x76, Supplementary_S_76},
	{0x77, Supplementary_S_77},
	{0x78, Supplementary_S_78},
	{0x79, Supplementary_S_79},
	{0x7A, Supplementary_S_7A},
	{0x7B, Supplementary_S_7B},
	{0x7C, Supplementary_S_7C},
	{0x7D, Supplementary_S_7D},
	{0x7E, Supplementary_S_7E},
	{0x80, Supplementary_S_80},
	{0x81, Supplementary_S_81},
	{0x83, Supplementary_S_83},
	{0x84, Supplementary_S_84},
	{0x85, Supplementary_S_85},
	{0x86, Supplementary_S_86},
	{0x88, Supplementary_S_88},
	{0x8D, Supplementary_S_8D},
	{0x8E, Supplementary_S_8E},
	{0x8F, Supplementary_S_8F},
	{0x90, Supplementary_S_90},
	{0x91, Supplementary_S_91},
	{0x92, Supplementary_S_92},
	{0x93, Supplementary_S_93},
	{0x94, Supplementary_S_94},
	{0x95, Supplementary_S_95},
	{0x96, Supplementary_S_96},
	{0x97, Supplementary_S_97},
	{0x98, Supplementary_S_98},
	{0x99, Supplementary_S_99},
	{0x9A, Supplementary_S_9A},
	{0x9B, Supplementary_S_9B},
	{0x9C, Supplementary_S_9C},
	{0x9D, Supplementary_S_9D},
	{0x9E, Supplementary_S_9E},
	{0x9F, Supplementary_S_9F},
	{0xA0, Supplementary_S_A0},
	{0xA1, Supplementary_S_A1},
	{0xA2, Supplementary_S_A2},
	{0xA3, Supplementary_S_A3},
	{0xA4, Supplementary_S_A4},
	{0xA5, Supplementary_S_A5},
	{0xA6, Supplementary_S_A6},
	{0xA7, Supplementary_S_A7},
	{0xA8, Supplementary_S_A8},
	{0xA9, Supplementary_S_A9},
	{0xAA, Supplementary_S_AA},
	{0xAB, Supplementary_S_AB},
	{0xAC, Supplementary_S_AC},
	{0xAD, Supplementary_S_AD},
	{0xAE, Supplementary_S_AE},
	{0xAF, Supplementary_S_AF},
	{0xB0, Supplementary_S_B0},
	{0xB1, Supplementary_S_B1},
	{0xB2, Supplementary_S_B2},
	{0xB3, Supplementary_S_B3},
	{0xB4, Supplementary_S_B4},
	{0xB5, Supplementary_S_B5},
	{0xB9, Supplementary_S_B9},
	{0xBF, Supplementary_S_BF},
	{0xC0, Supplementary_S_C0},
	{0xC3, Supplementary_S_C3},
	{0xC4, Supplementary_S_C4},
	{0xC5, Supplementary_S_C5},
	{0xC6, Supplementary_S_C6},
	{0xC7, Supplementary_S_C7},
	{0xC8, Supplementary_S_C8},
	{0xC9, Supplementary_S_C9},
	{0xCA, Supplementary_S_CA},
	{0xCB, Supplementary_S_CB},
	{0xCC, Supplementary_S_CC},
	{0xCD, Supplementary_S_CD},
	{0xCE, Supplementary_S_CE},
	{0xCF, Supplementary_S_CF},
	{0xD0, Supplementary_S_D0},
	{0xD1, Supplementary_S_D1},
	{0xD2, Supplementary_S_D2},
	{0xD3, Supplementary_S_D3},
	{0xD4, Supplementary_S_D4},
	{0xD5, Supplementary_S_D5},
	{0xD6, Supplementary_S_D6},
	{0xD7, Supplementary_S_D7},
	{0xD8, Supplementary_S_D8},
	{0xD9, Supplementary_S_D9},
	{0xDA, Supplementary_S_DA},
	{0xDB, Supplementary_S_DB},
	{0xDC, Supplementary_S_DC},
	{0xDD, Supplementary_S_DD},
	{0xDE, Supplementary_S_DE},
	{0xDF, Supplementary_S_DF},
	{0xE0, Supplementary_S_E0},
	{0xE1, Supplementary_S_E1},
	{0xE2, Supplementary_S_E2},
	{0xE3, Supplementary_S_E3},
	{0xE7, Supplementary_S_E7},
	{0xE8, Supplementary_S_E8},
	{0xE9, Supplementary_S_E9},
	{0xEA, Supplementary_S_EA},
	{0xEB, Supplementary_S_EB},
	{0xEC, Supplementary_S_EC},
	{0xED, Supplementary_S_ED},
	{0xEE, Supplementary_S_EE},
	{0xEF, Supplementary_S_EF},
	{0xF0, Supplementary_S_F0},
	{0xF1, Supplementary_S_F1},
	{0xF2, Supplementary_S_F2},
	{0xF3, Supplementary_S_F3},
	{0xF4, Supplementary_S_F4},
	{0xF5, Supplementary_S_F5},
	{0xF6, Supplementary_S_F6},
	{0xF7, Supplementary_S_F7},
	{0xF8, Supplementary_S_F8},
	{0xF9, Supplementary_S_F9},
	{0xFA, Supplementary_S_FA},
	{0xFB, Supplementary_S_FB},
	{0xFC, Supplementary_S_FC},
	{0xFD, Supplementary_S_FD},
	{0xFF, Supplementary_S_FF},
};

#endif