/*
 * ISO 14819-2 header file: supplementary information entries
 * DO NOT EDIT: automatically generated by gentables.py from CSV files
 */

#ifndef _ISO14819_2_SUPPLEMENTARY_H_INCLUDED
#define _ISO14819_2_SUPPLEMENTARY_H_INCLUDED
#ifdef WITH_RDS_TMC_SUPPLEMENTARY

#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
const char Supplementary_S_01[] PROGMEM = "heavy lorries are recommended to avoid the area";
const char Supplementary_S_02[] PROGMEM = "follow signs";
const char Supplementary_S_03[] PROGMEM = "follow diversion signs";
const char Supplementary_S_04[] PROGMEM = "diversion in operation";
const char Supplementary_S_05[] PROGMEM = "no suitable diversion available";
const char Supplementary_S_06[] PROGMEM = "diversion is no longer recommended";
const char Supplementary_S_07[] PROGMEM = "for exceptional loads only";
const char Supplementary_S_08[] PROGMEM = "for heavy vehicles only";
const char Supplementary_S_09[] PROGMEM = "for cars and light vehicles only";
const char Supplementary_S_0A[] PROGMEM = "snowploughs in use";
const char Supplementary_S_0B[] PROGMEM = "gritting vehicles in use";
const char Supplementary_S_0C[] PROGMEM = "drive carefully";
const char Supplementary_S_0D[] PROGMEM = "keep your distance";
const char Supplementary_S_0E[] PROGMEM = "observe signals";
const char Supplementary_S_0F[] PROGMEM = "overtake with care";
const char Supplementary_S_10[] PROGMEM = "cross junction with care";
const char Supplementary_S_11[] PROGMEM = "no overtaking";
const char Supplementary_S_12[] PROGMEM = "use headlights";
const char Supplementary_S_13[] PROGMEM = "use fog lights";
const char Supplementary_S_14[] PROGMEM = "do not leave your vehicle";
const char Supplementary_S_15[] PROGMEM = "switch off engine";
const char Supplementary_S_16[] PROGMEM = "close all windows. Turn off heater and vents";
const char Supplementary_S_17[] PROGMEM = "test your brakes";
const char Supplementary_S_18[] PROGMEM = "winter equipment recommended";
const char Supplementary_S_19[] PROGMEM = "snow chains recommended";
const char Supplementary_S_1A[] PROGMEM = "snow chains mandatory";
const char Supplementary_S_1B[] PROGMEM = "keep to the left";
const char Supplementary_S_1C[] PROGMEM = "keep to the right";
const char Supplementary_S_1D[] PROGMEM = "use hard shoulder as lane";
const char Supplementary_S_1E[] PROGMEM = "do not drive on the hard shoulder";
const char Supplementary_S_1F[] PROGMEM = "in the opposite direction";
const char Supplementary_S_20[] PROGMEM = "in the opposing lanes";
const char Supplementary_S_21[] PROGMEM = "in the overtaking lane";
const char Supplementary_S_22[] PROGMEM = "in the crawler lane";
const char Supplementary_S_23[] PROGMEM = "in the right lane";
const char Supplementary_S_24[] PROGMEM = "in the middle lane";
const char Supplementary_S_25[] PROGMEM = "in the left lane";
const char Supplementary_S_26[] PROGMEM = "on the roadway";
const char Supplementary_S_27[] PROGMEM = "police directing traffic";
const char Supplementary_S_28[] PROGMEM = "police in attendance";
const char Supplementary_S_29[] PROGMEM = "extra police patrols in operation";
const char Supplementary_S_2A[] PROGMEM = "rescue and recovery work in progress";
const char Supplementary_S_2B[] PROGMEM = "look out for flagman";
const char Supplementary_S_2C[] PROGMEM = "why not park-and-ride?";
const char Supplementary_S_2D[] PROGMEM = "why not try public transport?";
const char Supplementary_S_2E[] PROGMEM = "only travel if absolutely necessary";
const char Supplementary_S_2F[] PROGMEM = "increased risk of accident";
const char Supplementary_S_30[] PROGMEM = "on bridges";
const char Supplementary_S_31[] PROGMEM = "in shaded areas";
const char Supplementary_S_32[] PROGMEM = "entering or leaving tunnels";
const char Supplementary_S_33[] PROGMEM = "winter closure";
const char Supplementary_S_34[] PROGMEM = "batch service in progress";
const char Supplementary_S_35[] PROGMEM = "the north";
const char Supplementary_S_36[] PROGMEM = "the north-east";
const char Supplementary_S_37[] PROGMEM = "the east";
const char Supplementary_S_38[] PROGMEM = "the south-east";
const char Supplementary_S_39[] PROGMEM = "the south";
const char Supplementary_S_3A[] PROGMEM = "the south-west";
const char Supplementary_S_3B[] PROGMEM = "the west";
const char Supplementary_S_3C[] PROGMEM = "the north-west";
const char Supplementary_S_3D[] PROGMEM = "follow special diversion markers";
const char Supplementary_S_3E[] PROGMEM = "do not follow diversion signs";
const char Supplementary_S_3F[] PROGMEM = "follow local diversion";
const char Supplementary_S_40[] PROGMEM = "compulsory diversion in operation";
const char Supplementary_S_41[] PROGMEM = "for petrol-engined vehicles only";
const char Supplementary_S_42[] PROGMEM = "for diesel-engined vehicles only";
const char Supplementary_S_43[] PROGMEM = "for LPG vehicles only";
const char Supplementary_S_44[] PROGMEM = "local drivers are recommended to avoid the area";
const char Supplementary_S_45[] PROGMEM = "for 4-wheel-drive with snow tyres or chains only";
const char Supplementary_S_46[] PROGMEM = "in the median";
const char Supplementary_S_47[] PROGMEM = "for cars only";
const char Supplementary_S_48[] PROGMEM = "for light vehicles only";
const char Supplementary_S_49[] PROGMEM = "for vehicles with catalytic converters";
const char Supplementary_S_4A[] PROGMEM = "for vehicles without catalytic converters";
const char Supplementary_S_4B[] PROGMEM = "for cars with trailers only";
const char Supplementary_S_4C[] PROGMEM = "for cars with caravans only";
const char Supplementary_S_4D[] PROGMEM = "for vehicles with trailers only";
const char Supplementary_S_4E[] PROGMEM = "for heavy lorries only";
const char Supplementary_S_4F[] PROGMEM = "for buses only";
const char Supplementary_S_50[] PROGMEM = "for articulated vehicles only";
const char Supplementary_S_51[] PROGMEM = "for high-sided vehicles only";
const char Supplementary_S_52[] PROGMEM = "for hazardous loads only";
const char Supplementary_S_53[] PROGMEM = "for abnormal loads only";
const char Supplementary_S_54[] PROGMEM = "with even-numbered registration plates";
const char Supplementary_S_55[] PROGMEM = "with odd-numbered registration plates";
const char Supplementary_S_56[] PROGMEM = "for all vehicles";
const char Supplementary_S_58[] PROGMEM = "for through traffic";
const char Supplementary_S_59[] PROGMEM = "for rail services";
const char Supplementary_S_5A[] PROGMEM = "on the underground";
const char Supplementary_S_5B[] PROGMEM = "danger";
const char Supplementary_S_5C[] PROGMEM = "repairs in progress";
const char Supplementary_S_5D[] PROGMEM = "pilot car in operation";
const char Supplementary_S_5E[] PROGMEM = "emergency vehicles at scene";
const char Supplementary_S_5F[] PROGMEM = "traffic being directed around accident area";
const char Supplementary_S_60[] PROGMEM = "danger of explosion";
const char Supplementary_S_61[] PROGMEM = "danger of fire";
const char Supplementary_S_62[] PROGMEM = "radiation hazard";
const char Supplementary_S_63[] PROGMEM = "toxic leak";
const char Supplementary_S_64[] PROGMEM = "firemen directing traffic";
const char Supplementary_S_65[] PROGMEM = "police speed checks in operation";
const char Supplementary_S_66[] PROGMEM = "mandatory speed limit in force";
const char Supplementary_S_67[] PROGMEM = "speed limit in force for heavy vehicles";
const char Supplementary_S_68[] PROGMEM = "reduce your speed";
const char Supplementary_S_69[] PROGMEM = "observe speed limits";
const char Supplementary_S_6A[] PROGMEM = "observe recommended speed";
const char Supplementary_S_6B[] PROGMEM = "snow chains required";
const char Supplementary_S_6C[] PROGMEM = "snow chains or tyres reqired";
const char Supplementary_S_6D[] PROGMEM = "helicopter rescue in progress";
const char Supplementary_S_6E[] PROGMEM = "several accidents have taken place";
const char Supplementary_S_6F[] PROGMEM = "drive with extreme caution";
const char Supplementary_S_70[] PROGMEM = "approach with care";
const char Supplementary_S_71[] PROGMEM = "increase normal following distance";
const char Supplementary_S_72[] PROGMEM = "do not allow unnecessary gaps";
const char Supplementary_S_73[] PROGMEM = "follow the vehicle in front, smoothly";
const char Supplementary_S_74[] PROGMEM = "do not slow down unneccessarily";
const char Supplementary_S_75[] PROGMEM = "observe signs";
const char Supplementary_S_76[] PROGMEM = "use hazard warning lights";
const char Supplementary_S_77[] PROGMEM = "no smoking";
const char Supplementary_S_78[] PROGMEM = "no naked flames";
const char Supplementary_S_79[] PROGMEM = "switch off mobile phones and two-way radios";
const char Supplementary_S_7A[] PROGMEM = "allow emergency vehicles to pass";
const char Supplementary_S_7B[] PROGMEM = "clear a lane for emergency vehicles";
const char Supplementary_S_7C[] PROGMEM = "pull over to the edge of the roadway";
const char Supplementary_S_7D[] PROGMEM = "wait for escort vehicle";
const char Supplementary_S_7E[] PROGMEM = "in emergency, wait for police patrol";
const char Supplementary_S_80[] PROGMEM = "stop at next safe place";
const char Supplementary_S_81[] PROGMEM = "clear a lane for snowploughs and gritting vehicles";
const char Supplementary_S_83[] PROGMEM = "use right lane";
const char Supplementary_S_84[] PROGMEM = "use left lane";
const char Supplementary_S_85[] PROGMEM = "heavy vehicles use right lane";
const char Supplementary_S_86[] PROGMEM = "heavy vehicles use left lane";
const char Supplementary_S_88[] PROGMEM = "stop at next service area";
const char Supplementary_S_8D[] PROGMEM = "on the right";
const char Supplementary_S_8E[] PROGMEM = "in the centre";
const char Supplementary_S_8F[] PROGMEM = "on the left";
const char Supplementary_S_90[] PROGMEM = "in the bus lane";
const char Supplementary_S_91[] PROGMEM = "in the carpool lane";
const char Supplementary_S_92[] PROGMEM = "on the hard shoulder";
const char Supplementary_S_93[] PROGMEM = "in the emergency lane";
const char Supplementary_S_94[] PROGMEM = "on the opposite carriageway";
const char Supplementary_S_95[] PROGMEM = "in the heavy vehicle lane";
const char Supplementary_S_96[] PROGMEM = "in the local lane";
const char Supplementary_S_97[] PROGMEM = "due to heat";
const char Supplementary_S_98[] PROGMEM = "due to frost";
const char Supplementary_S_99[] PROGMEM = "for ferry service";
const char Supplementary_S_9A[] PROGMEM = "for roads in";
const char Supplementary_S_9B[] PROGMEM = "in the through traffic lane";
const char Supplementary_S_9C[] PROGMEM = "in the express lane";
const char Supplementary_S_9D[] PROGMEM = "in the connecting carriageway";
const char Supplementary_S_9E[] PROGMEM = "in the parallel carriageway";
const char Supplementary_S_9F[] PROGMEM = "in the right-hand parallel carriageway";
const char Supplementary_S_A0[] PROGMEM = "in the left-hand parallel carriageway";
const char Supplementary_S_A1[] PROGMEM = "in tunnels";
const char Supplementary_S_A2[] PROGMEM = "on slip roads";
const char Supplementary_S_A3[] PROGMEM = "at high altitudes";
const char Supplementary_S_A4[] PROGMEM = "in low-lying areas";
const char Supplementary_S_A5[] PROGMEM = "around a bend in the road";
const char Supplementary_S_A6[] PROGMEM = "over the crest of a hill";
const char Supplementary_S_A7[] PROGMEM = "in the city centre";
const char Supplementary_S_A8[] PROGMEM = "in the inner city area";
const char Supplementary_S_A9[] PROGMEM = "in the slow vehicle lane";
const char Supplementary_S_AA[] PROGMEM = "in the turning lane";
const char Supplementary_S_AB[] PROGMEM = "due to an earlier accident";
const char Supplementary_S_AC[] PROGMEM = "due to shear weight of traffic";
const char Supplementary_S_AD[] PROGMEM = "due to large numbers of visitors";
const char Supplementary_S_AE[] PROGMEM = "due to holiday traffic";
const char Supplementary_S_AF[] PROGMEM = "due to technical problems";
const char Supplementary_S_B0[] PROGMEM = "towards town";
const char Supplementary_S_B1[] PROGMEM = "from town";
const char Supplementary_S_B2[] PROGMEM = "on entry into the country";
const char Supplementary_S_B3[] PROGMEM = "on leaving the country";
const char Supplementary_S_B4[] PROGMEM = "do not throw out any burning objects";
const char Supplementary_S_B5[] PROGMEM = "traffic wardens directing traffic";
const char Supplementary_S_B9[] PROGMEM = "due to falling ice";
const char Supplementary_S_BF[] PROGMEM = "snow tyres recommended";
const char Supplementary_S_C0[] PROGMEM = "snow tyres mandatory";
const char Supplementary_S_C3[] PROGMEM = "use through traffic lanes";
const char Supplementary_S_C4[] PROGMEM = "use local traffic lanes";
const char Supplementary_S_C5[] PROGMEM = "use left-hand parallel carriageway";
const char Supplementary_S_C6[] PROGMEM = "use right-hand parallel carriageway";
const char Supplementary_S_C7[] PROGMEM = "use heavy vehicle lane";
const char Supplementary_S_C8[] PROGMEM = "due to an earlier incident";
const char Supplementary_S_C9[] PROGMEM = "why not ride share?";
const char Supplementary_S_CA[] PROGMEM = "is this your no-ride day?";
const char Supplementary_S_CB[] PROGMEM = "due to an earlier event";
const char Supplementary_S_CC[] PROGMEM = "please use rail service";
const char Supplementary_S_CD[] PROGMEM = "please use underground service";
const char Supplementary_S_CE[] PROGMEM = "please use tram service";
const char Supplementary_S_CF[] PROGMEM = "please use bus service";
const char Supplementary_S_D0[] PROGMEM = "for a limited time";
const char Supplementary_S_D1[] PROGMEM = "your parking ticket covers the return ride";
const char Supplementary_S_D2[] PROGMEM = "avoid the rush hour";
const char Supplementary_S_D3[] PROGMEM = "for holiday traffic";
const char Supplementary_S_D4[] PROGMEM = "for residents";
const char Supplementary_S_D5[] PROGMEM = "several times";
const char Supplementary_S_D6[] PROGMEM = "during the day time";
const char Supplementary_S_D7[] PROGMEM = "during off-peak periods";
const char Supplementary_S_D8[] PROGMEM = "during the night";
const char Supplementary_S_D9[] PROGMEM = "until further notice";
const char Supplementary_S_DA[] PROGMEM = "for arrivals";
const char Supplementary_S_DB[] PROGMEM = "for departures";
const char Supplementary_S_DC[] PROGMEM = "access only";
const char Supplementary_S_DD[] PROGMEM = "only";
const char Supplementary_S_DE[] PROGMEM = "except";
const char Supplementary_S_DF[] PROGMEM = "for long distance traffic";
const char Supplementary_S_E0[] PROGMEM = "for local traffic";
const char Supplementary_S_E1[] PROGMEM = "for regional traffic";
const char Supplementary_S_E2[] PROGMEM = "unconfirmed report";
const char Supplementary_S_E3[] PROGMEM = "on manual payment lanes";
const char Supplementary_S_E7[] PROGMEM = "sorry for any delay";
const char Supplementary_S_E8[] PROGMEM = "for roads leading towards";
const char Supplementary_S_E9[] PROGMEM = "for roads from";
const char Supplementary_S_EA[] PROGMEM = "we are grateful for your cooperation";
const char Supplementary_S_EB[] PROGMEM = "Traffic queue length decreasing at an average rate of 10 km/hr";
const char Supplementary_S_EC[] PROGMEM = "Traffic queue length decreasing at an average rate of 20 km/hr";
const char Supplementary_S_ED[] PROGMEM = "Traffic queue length decreasing at an average rate of 30 km/hr";
const char Supplementary_S_EE[] PROGMEM = "Traffic queue length decreasing at an average rate of 40 km/hr";
const char Supplementary_S_EF[] PROGMEM = "leave your vehicle. Proceed to next save place";
const char Supplementary_S_F0[] PROGMEM = "for visitors";
const char Supplementary_S_F1[] PROGMEM = "in the roadworks area";
const char Supplementary_S_F2[] PROGMEM = "from";
const char Supplementary_S_F3[] PROGMEM = "to";
const char Supplementary_S_F4[] PROGMEM = "in";
const char Supplementary_S_F5[] PROGMEM = "Traffic queue length increasing";
const char Supplementary_S_F6[] PROGMEM = "Traffic queue length increasing at an average rate of 10 km/hr";
const char Supplementary_S_F7[] PROGMEM = "Traffic queue length increasing at an average rate of 20 km/hr";
const char Supplementary_S_F8[] PROGMEM = "Traffic queue length increasing at an average rate of 30 km/hr";
const char Supplementary_S_F9[] PROGMEM = "Traffic queue length increasing at an average rate of 40 km/hr";
const char Supplementary_S_FA[] PROGMEM = "very frequent service";
const char Supplementary_S_FB[] PROGMEM = "frequent service";
const char Supplementary_S_FC[] PROGMEM = "fairly frequent service";
const char Supplementary_S_FD[] PROGMEM = "regular service";
const char Supplementary_S_FF[] PROGMEM = "Traffic queue length decreasing";
#endif

const TRDSTMCSupplementaryEntry ISO14819_2_Supplementary[233] PROGMEM = {
	{0x01
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_01
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0000
#endif
},
	{0x02
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_02
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0030
#endif
},
	{0x03
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_03
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x003D
#endif
},
	{0x04
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_04
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0054
#endif
},
	{0x05
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_05
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x006B
#endif
},
	{0x06
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_06
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x008B
#endif
},
	{0x07
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_07
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x00AE
#endif
},
	{0x08
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_08
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x00C9
#endif
},
	{0x09
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_09
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x00E1
#endif
},
	{0x0A
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_0A
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0102
#endif
},
	{0x0B
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_0B
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0115
#endif
},
	{0x0C
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_0C
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x012E
#endif
},
	{0x0D
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_0D
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x013E
#endif
},
	{0x0E
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_0E
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0151
#endif
},
	{0x0F
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_0F
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0161
#endif
},
	{0x10
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_10
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0174
#endif
},
	{0x11
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_11
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x018D
#endif
},
	{0x12
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_12
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x019B
#endif
},
	{0x13
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_13
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x01AA
#endif
},
	{0x14
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_14
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x01B9
#endif
},
	{0x15
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_15
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x01D3
#endif
},
	{0x16
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_16
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x01E5
#endif
},
	{0x17
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_17
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0212
#endif
},
	{0x18
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_18
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0223
#endif
},
	{0x19
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_19
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0240
#endif
},
	{0x1A
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_1A
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0258
#endif
},
	{0x1B
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_1B
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x026E
#endif
},
	{0x1C
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_1C
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x027F
#endif
},
	{0x1D
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_1D
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0291
#endif
},
	{0x1E
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_1E
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x02AB
#endif
},
	{0x1F
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_1F
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x02CD
#endif
},
	{0x20
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_20
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x02E7
#endif
},
	{0x21
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_21
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x02FD
#endif
},
	{0x22
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_22
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0314
#endif
},
	{0x23
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_23
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0328
#endif
},
	{0x24
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_24
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x033A
#endif
},
	{0x25
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_25
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x034D
#endif
},
	{0x26
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_26
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x035E
#endif
},
	{0x27
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_27
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x036D
#endif
},
	{0x28
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_28
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0386
#endif
},
	{0x29
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_29
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x039B
#endif
},
	{0x2A
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_2A
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x03BD
#endif
},
	{0x2B
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_2B
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x03E2
#endif
},
	{0x2C
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_2C
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x03F7
#endif
},
	{0x2D
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_2D
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x040E
#endif
},
	{0x2E
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_2E
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x042C
#endif
},
	{0x2F
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_2F
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0450
#endif
},
	{0x30
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_30
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x046B
#endif
},
	{0x31
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_31
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0476
#endif
},
	{0x32
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_32
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0486
#endif
},
	{0x33
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_33
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x04A2
#endif
},
	{0x34
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_34
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x04B1
#endif
},
	{0x35
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_35
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x04CB
#endif
},
	{0x36
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_36
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x04D5
#endif
},
	{0x37
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_37
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x04E4
#endif
},
	{0x38
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_38
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x04ED
#endif
},
	{0x39
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_39
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x04FC
#endif
},
	{0x3A
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_3A
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0506
#endif
},
	{0x3B
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_3B
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0515
#endif
},
	{0x3C
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_3C
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x051E
#endif
},
	{0x3D
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_3D
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x052D
#endif
},
	{0x3E
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_3E
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x054E
#endif
},
	{0x3F
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_3F
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x056C
#endif
},
	{0x40
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_40
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0583
#endif
},
	{0x41
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_41
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x05A5
#endif
},
	{0x42
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_42
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x05C6
#endif
},
	{0x43
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_43
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x05E7
#endif
},
	{0x44
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_44
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x05FD
#endif
},
	{0x45
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_45
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x062D
#endif
},
	{0x46
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_46
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x065E
#endif
},
	{0x47
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_47
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x066C
#endif
},
	{0x48
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_48
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x067A
#endif
},
	{0x49
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_49
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0692
#endif
},
	{0x4A
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_4A
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x06B9
#endif
},
	{0x4B
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_4B
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x06E3
#endif
},
	{0x4C
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_4C
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x06FF
#endif
},
	{0x4D
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_4D
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x071B
#endif
},
	{0x4E
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_4E
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x073B
#endif
},
	{0x4F
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_4F
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0752
#endif
},
	{0x50
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_50
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0761
#endif
},
	{0x51
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_51
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x077F
#endif
},
	{0x52
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_52
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x079C
#endif
},
	{0x53
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_53
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x07B5
#endif
},
	{0x54
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_54
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x07CD
#endif
},
	{0x55
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_55
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x07F4
#endif
},
	{0x56
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_56
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x081A
#endif
},
	{0x58
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_58
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x082B
#endif
},
	{0x59
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_59
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x083F
#endif
},
	{0x5A
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_5A
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0851
#endif
},
	{0x5B
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_5B
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0864
#endif
},
	{0x5C
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_5C
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x086B
#endif
},
	{0x5D
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_5D
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x087F
#endif
},
	{0x5E
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_5E
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0896
#endif
},
	{0x5F
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_5F
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x08B2
#endif
},
	{0x60
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_60
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x08DE
#endif
},
	{0x61
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_61
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x08F2
#endif
},
	{0x62
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_62
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0901
#endif
},
	{0x63
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_63
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0912
#endif
},
	{0x64
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_64
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x091D
#endif
},
	{0x65
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_65
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0937
#endif
},
	{0x66
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_66
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0958
#endif
},
	{0x67
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_67
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0977
#endif
},
	{0x68
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_68
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x099F
#endif
},
	{0x69
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_69
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x09B1
#endif
},
	{0x6A
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_6A
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x09C6
#endif
},
	{0x6B
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_6B
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x09E0
#endif
},
	{0x6C
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_6C
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x09F5
#endif
},
	{0x6D
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_6D
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0A12
#endif
},
	{0x6E
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_6E
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0A30
#endif
},
	{0x6F
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_6F
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0A53
#endif
},
	{0x70
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_70
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0A6E
#endif
},
	{0x71
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_71
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0A81
#endif
},
	{0x72
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_72
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0AA4
#endif
},
	{0x73
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_73
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0AC2
#endif
},
	{0x74
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_74
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0AE8
#endif
},
	{0x75
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_75
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0B08
#endif
},
	{0x76
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_76
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0B16
#endif
},
	{0x77
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_77
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0B30
#endif
},
	{0x78
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_78
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0B3B
#endif
},
	{0x79
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_79
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0B4B
#endif
},
	{0x7A
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_7A
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0B77
#endif
},
	{0x7B
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_7B
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0B98
#endif
},
	{0x7C
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_7C
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0BBC
#endif
},
	{0x7D
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_7D
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0BE1
#endif
},
	{0x7E
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_7E
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0BF9
#endif
},
	{0x80
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_80
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0C1E
#endif
},
	{0x81
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_81
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0C36
#endif
},
	{0x83
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_83
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0C69
#endif
},
	{0x84
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_84
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0C78
#endif
},
	{0x85
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_85
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0C86
#endif
},
	{0x86
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_86
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0CA4
#endif
},
	{0x88
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_88
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0CC1
#endif
},
	{0x8D
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_8D
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0CDB
#endif
},
	{0x8E
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_8E
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0CE8
#endif
},
	{0x8F
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_8F
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0CF6
#endif
},
	{0x90
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_90
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0D02
#endif
},
	{0x91
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_91
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0D12
#endif
},
	{0x92
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_92
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0D26
#endif
},
	{0x93
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_93
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0D3B
#endif
},
	{0x94
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_94
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0D51
#endif
},
	{0x95
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_95
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0D6D
#endif
},
	{0x96
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_96
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0D87
#endif
},
	{0x97
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_97
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0D99
#endif
},
	{0x98
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_98
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0DA5
#endif
},
	{0x99
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_99
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0DB2
#endif
},
	{0x9A
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_9A
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0DC4
#endif
},
	{0x9B
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_9B
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0DD1
#endif
},
	{0x9C
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_9C
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0DED
#endif
},
	{0x9D
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_9D
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0E01
#endif
},
	{0x9E
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_9E
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0E1F
#endif
},
	{0x9F
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_9F
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0E3B
#endif
},
	{0xA0
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_A0
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0E62
#endif
},
	{0xA1
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_A1
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0E88
#endif
},
	{0xA2
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_A2
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0E93
#endif
},
	{0xA3
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_A3
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0EA1
#endif
},
	{0xA4
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_A4
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0EB3
#endif
},
	{0xA5
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_A5
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0EC6
#endif
},
	{0xA6
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_A6
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0EE0
#endif
},
	{0xA7
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_A7
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0EF9
#endif
},
	{0xA8
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_A8
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0F0C
#endif
},
	{0xA9
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_A9
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0F23
#endif
},
	{0xAA
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_AA
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0F3C
#endif
},
	{0xAB
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_AB
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0F50
#endif
},
	{0xAC
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_AC
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0F6B
#endif
},
	{0xAD
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_AD
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0F8A
#endif
},
	{0xAE
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_AE
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0FAB
#endif
},
	{0xAF
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_AF
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0FC2
#endif
},
	{0xB0
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_B0
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0FDC
#endif
},
	{0xB1
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_B1
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0FE9
#endif
},
	{0xB2
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_B2
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x0FF3
#endif
},
	{0xB3
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_B3
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x100D
#endif
},
	{0xB4
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_B4
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1024
#endif
},
	{0xB5
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_B5
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1049
#endif
},
	{0xB9
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_B9
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x106B
#endif
},
	{0xBF
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_BF
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x107E
#endif
},
	{0xC0
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_C0
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1095
#endif
},
	{0xC3
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_C3
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x10AA
#endif
},
	{0xC4
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_C4
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x10C4
#endif
},
	{0xC5
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_C5
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x10DC
#endif
},
	{0xC6
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_C6
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x10FF
#endif
},
	{0xC7
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_C7
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1123
#endif
},
	{0xC8
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_C8
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x113A
#endif
},
	{0xC9
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_C9
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1155
#endif
},
	{0xCA
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_CA
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1169
#endif
},
	{0xCB
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_CB
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1183
#endif
},
	{0xCC
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_CC
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x119B
#endif
},
	{0xCD
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_CD
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x11B3
#endif
},
	{0xCE
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_CE
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x11D2
#endif
},
	{0xCF
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_CF
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x11EA
#endif
},
	{0xD0
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_D0
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1201
#endif
},
	{0xD1
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_D1
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1214
#endif
},
	{0xD2
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_D2
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x123F
#endif
},
	{0xD3
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_D3
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1253
#endif
},
	{0xD4
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_D4
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1267
#endif
},
	{0xD5
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_D5
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1275
#endif
},
	{0xD6
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_D6
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1283
#endif
},
	{0xD7
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_D7
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1297
#endif
},
	{0xD8
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_D8
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x12AF
#endif
},
	{0xD9
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_D9
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x12C0
#endif
},
	{0xDA
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_DA
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x12D5
#endif
},
	{0xDB
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_DB
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x12E2
#endif
},
	{0xDC
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_DC
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x12F1
#endif
},
	{0xDD
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_DD
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x12FD
#endif
},
	{0xDE
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_DE
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1302
#endif
},
	{0xDF
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_DF
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1309
#endif
},
	{0xE0
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_E0
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1323
#endif
},
	{0xE1
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_E1
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1335
#endif
},
	{0xE2
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_E2
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x134A
#endif
},
	{0xE3
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_E3
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x135D
#endif
},
	{0xE7
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_E7
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1375
#endif
},
	{0xE8
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_E8
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1389
#endif
},
	{0xE9
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_E9
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x13A3
#endif
},
	{0xEA
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_EA
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x13B2
#endif
},
	{0xEB
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_EB
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x13D7
#endif
},
	{0xEC
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_EC
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1416
#endif
},
	{0xED
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_ED
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1455
#endif
},
	{0xEE
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_EE
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1494
#endif
},
	{0xEF
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_EF
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x14D3
#endif
},
	{0xF0
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_F0
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1502
#endif
},
	{0xF1
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_F1
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x150F
#endif
},
	{0xF2
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_F2
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1525
#endif
},
	{0xF3
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_F3
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x152A
#endif
},
	{0xF4
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_F4
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x152D
#endif
},
	{0xF5
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_F5
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1530
#endif
},
	{0xF6
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_F6
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1550
#endif
},
	{0xF7
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_F7
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x158F
#endif
},
	{0xF8
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_F8
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x15CE
#endif
},
	{0xF9
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_F9
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x160D
#endif
},
	{0xFA
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_FA
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x164C
#endif
},
	{0xFB
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_FB
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1662
#endif
},
	{0xFC
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_FC
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x1673
#endif
},
	{0xFD
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_FD
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x168B
#endif
},
	{0xFF
#if defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_FLASH)
, Supplementary_S_FF
#elif defined(WITH_RDS_TMC_SUPPLEMENTARY_STRINGS_EEPROM)
, (const char * const) 0x169B
#endif
},
};

#endif
#endif